version: '2'
services:
 minio1:
  image: minio/minio
  volumes:
   - data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio2:
  image: minio/minio
  volumes:
   - data2:/data
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio3:
  image: minio/minio
  volumes:
   - data3:/data
  ports:
   - "9003:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio4:
  image: minio/minio
  volumes:
   - data4:/data
  ports:
   - "9004:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

volumes:
  data1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/minio1-data/
  data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/minio2-data/
  data3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/minio3-data/
  data4:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/minio4-data/
